Working at cleaning up the script a bit per @AlexDaniel's link to http://mywiki.wooledge.org/BashPitfalls. Ironically I have been sent this link before and forgotten where it was. I'm glad to have found it again. I'm intending on doing more cleanups. If there are any suggestions based on the changes please add a comment.
- Cleaning up the 'INSTALL' script.
- Moving DEB Package lists into 'conf/packages.debs' and 'conf/dependencies.debs'.
- Moving BunsenLabs repo list into 'conf/bunsenlabs.repos'.
- Moving Rsync exclusion list into 'conf/rsync.exclusions'.
- Updated 'lib/githubtar' to use the $TMPPATH defined in 'INSTALL'.
- Added 'lib/mktempdir' which uses `mktempdir` if it is available; falls back to `mkdir -p "/tmp/$(date -u '+%s')-BunsenLabs"`.

diff --git a/INSTALL b/INSTALL
--- a/INSTALL
+++ b/INSTALL
@@ -1,21 +1,30 @@
-#!/bin/bash -f
+#!/bin/bash -e
 
 # Environment Variables
-PATH=$(dirname $0)/lib:$PATH
-: ${TMPPATH:="/tmp/bunsenlabs"}
+CONFPATH="$(dirname $0)/conf"
+PATH="$(dirname $0)/lib:${PATH}"
+DEBIAN_FRONTEND="noninteractive"
+mkdir -p "${TMPPATH:="$(mktempdir)"}"
+
+# Aliases
+alias rsync="command rsync --exclude-from \"${CONFPATH}/rsync.exclusions\" -abviuzP"
+alias install="apt-get --no-install-recommends --no-install-suggests --force-yes install"
+# @NOTE A dist-upgrade is nonsafe as it could break other environments.
+alias upgrade="apt-get --no-install-recommends --no-install-suggests --force-yes upgrade"
+alias update="apt-get update"
 
 # Cleanup the installer
-function cleanup() { rm -Rf $TMPPATH; }
+#function cleanup() { rm -Rf "$TMPPATH"; }
+alias cleanup="rm -Rf \"${TMPPATH}\""
 trap "cleanup" EXIT SIGQUIT SIGKILL
 
 #######################
 # Step A - Check Root #
 #######################
-if [[ $(id -u) > 0 ]]; then
+if [[ "$(id -u)" -gt 0 ]]; then
    echo "This install script must be run as root" 1>&2
    exit 1
 fi
-
 
 ####################
 # Step B - Welcome #
@@ -25,49 +34,50 @@ if ! whiptail --backtitle "BunsenLabs" \
 	--yesno "Welcome to Bunsen Labs Linux installation!\n(WARNING THIS IS STILL UNDERGOING TESTING)" 8 65 \
 	--yes-button "Start Installation" \
 	--no-button "Cancel"; then
+  clear
 	exit 1
 fi
 
 clear
 
-
 #######################
 # Step C - Update apt #
 #######################
-if ! apt-get update; then
+if ! update; then
 	whiptail --backtitle "BunsenLabs" \
 		--title "Install Failed" \
 		--msgbox "Could not update the apt repositories. Please check to ensure your repositories are setup correctly." 8 65 \
 		--ok-button "Exit"
+    clear
 		exit 1
 fi
 
 clear
-
 
 ###################################################
 # Step 1 - Installation Dependencies              #
 # Let's promote transparency of actions shall we? #
 # => See install() for details.                   #
 ###################################################
-if whiptail --backtitle "BunsenLabs" \
+if ! whiptail --backtitle "BunsenLabs" \
 	--title "Install Dependencies" \
 	--yesno "In order to install we need to ensure rsync and curl are available.\nMay we install Rsync, Curl and any other required dependencies with:\n\`apt-get install --no-install-recommends --no-install-suggests --force-yes rsync curl bc\`" 9 65 \
 	--yes-button "Install" \
 	--no-button "Exit Installation"; then
-
-	apt-get install --no-install-recommends --no-install-suggests --force-yes rsync curl bc
-else
 	clear
 	exit 1
 fi
 
+xargs < "${CONFPATH}/dependencies.debs" install
+
+clear
 
 ###########################################
 # Step 2 - Bunsel Configurations Download #
 ###########################################
+xargs -n1 < "${CONFPATH}/bunsen.repos" githubtar -r
+
 clear
-xargs -n1 < bunsenfiles.txt githubtar -r $repo
 
 ###########################################
 # Step 3 - Place BunsenLabs configuration #
@@ -80,36 +90,40 @@ clear
 echo "Moving system files..."
 sleep 2
 
-rm -r /etc/skel
-mkdir /etc/skel
+# @TODO Consider why we are deleting the /etc/skel directory.
+#       If I'm installing BunsenLabs as an alternative user environment
+#       This is extremely counter intuitive.
+#rm -r /etc/skel
+#mkdir /etc/skel
+
 # removes default debian default home directory install and makes space for config files
-rsync --exclude-from 'exclude.txt'  -abviuzP /tmp/bunsenlabs/bunsen-installscripts/systemfiles/. /
+rsync "${TMPPATH}/repos/bunsen-installscripts/systemfiles/." "/"
 #copies some system files
-rsync --exclude-from 'exclude.txt'  -abviuzP /tmp/bunsenlabs/bunsen1-dark-theme-master /usr/share/themes
-rsync --exclude-from 'exclude.txt'  -abviuzP /tmp/bunsenlabs/deb8-theme-master  /usr/share/themes
-rsync --exclude-from 'exclude.txt'  -abviuzP /tmp/bunsenlabs/bunsen1-theme-master/Bunsen1 /usr/share/themes
+rsync "${TMPPATH}/repos/bunsen1-dark-theme-master" "/usr/share/themes"
+rsync "${TMPPATH}/repos/deb8-theme-master" "/usr/share/themes"
+rsync "${TMPPATH}/repos/bunsen1-theme-master/Bunsen1" "/usr/share/themes"
 #copies over themes
-rsync --exclude-from 'exclude.txt'  -abviuzP /tmp/bunsenlabs/bunsen-configs-master/. /etc/skel
+rsync "${TMPPATH}/repos/bunsen-configs-master/." "/etc/skel"
 # copies config files
 mkdir /etc/skel/conky-BL
-rsync --exclude-from 'exclude.txt'  -abviuzP /tmp/bunsenlabs/bunsen-conky-master/. /etc/skel/conky-BL
+rsync "${TMPPATH}/repos/bunsen-conky-master/." "/etc/skel/conky-BL"
 # conky installation
-rsync --exclude-from 'exclude.txt'  -abviuzP /tmp/bunsenlabs/bunsen-docs-master/. /usr/share/doc
+rsync "${TMPPATH}/repos/bunsen-docs-master/." "/usr/share/doc"
 # installs docs
-rsync --exclude-from 'exclude.txt'  -abviuzP /tmp/bunsenlabs/bunsen-pipemenus-master/. /usr/bin
+rsync "${TMPPATH}/repos/bunsen-pipemenus-master/." "/usr/bin"
 # installs pipemenus
-rsync --exclude-from 'exclude.txt'  -abviuzP /tmp/bunsenlabs/bunsen-exit-master/. /usr/bin
+rsync "${TMPPATH}/repos/bunsen-exit-master/." "/usr/bin"
 # installs bl-exit
 mkdir /usr/share/backgrounds
-rsync --exclude-from 'exclude.txt'  -abviuzP /tmp/bunsenlabs/bunsen1-theme-master/Wallpapers/. /usr/share/backgrounds
-rsync --exclude-from 'exclude.txt'  -abviuzP /tmp/bunsenlabs/bunsen-images-master/. /usr/share/backgrounds
+rsync "${TMPPATH}/repos/bunsen1-theme-master/Wallpapers/." "/usr/share/backgrounds"
+rsync "${TMPPATH}/repos/bunsen-images-master/." "/usr/share/backgrounds"
 # installs wallpaper set
-rsync --exclude-from 'exclude.txt'  -abviuzP /tmp/bunsenlabs/bunsen-wmhacks-master/. /usr/bin
+rsync "${TMPPATH}/repos/bunsen-wmhacks-master/." "/usr/bin"
 # installs wm hacks
-rsync --exclude-from 'exclude.txt'  -abviuzP /tmp/bunsenlabs/bunsen-lock-master/. /usr/bin
+rsync "${TMPPATH}/repos/bunsen-lock-master/." "/usr/bin"
 # installs bunsen-lock
 mkdir /usr/lib/bunsen/bunsen-common
-rsync --exclude-from 'exclude.txt'  -abviuzP bunsen-common-master/. /usr/lib/bunsen/bunsen-common
+rsync "${TMPPATH}/repos/bunsen-common-master/." "/usr/lib/bunsen/bunsen-common"
 clear
 
 echo "Updating debian..."
@@ -142,13 +156,14 @@ clear
 #read USER
 #export USER
 #install john raff script
-#rsync --exclude-from 'exclude.txt'  -abviuzP /tmp/bunsenlabs/bunsen-user-setup-master/bl-user-setup /home/$USER/.config/bunsen/bl-setup
+#rsync --exclude-from "${CONFPATH}/rsync.exclusions" \
+  -abviuzP ${TMPPATH}/repos/bunsen-user-setup-master/bl-user-setup /home/$USER/.config/bunsen/bl-setup
 
 ####### John Raff bl-user-setup script
 # BunsenLabs User Set-up
 
 # USER="$1" USER is exported by lightdm
-#rsync --exclude-from 'exclude.txt' -abviuzP /etc/skel/. /home/$USER
+#rsync --exclude-from "${CONFPATH}/rsync.exclusions" -abviuzP /etc/skel/. /home/$USER
 
 #[ -f "/home/$USER/.gtk-bookmarks" ] && {
 #    rpl -q 'REPLACEME' $USER /home/$USER/.gtk-bookmarks > /dev/null 2>&1
diff --git a/lib/githubtar b/lib/githubtar
--- a/lib/githubtar
+++ b/lib/githubtar
@@ -1,11 +1,11 @@
-#!/bin/bash
+#!/bin/bash -e
 
 : ${REF:="master"}
-: ${DESTDIR:="/tmp/bunsenlabs"}
 : ${DLMETHOD:="curl"}
+: ${TMPPATH:="$(./mktempdir)"}
 
-while getopts ":r:b:t:e:g" opt; do
-  case $opt in
+while getopts ":r:b:t:e:g" OPTION; do
+  case $OPTION in
     g)
       DLMETHOD="git"
       ;;
@@ -19,27 +19,27 @@ while getopts ":r:b:t:e:g" opt; do
       DESTDIR="$OPTARG"
       ;;
     *)
-      echo "github(): invalid option -$opt" >&2
+      echo "github(): invalid option -$OPTION" >&2
       ;;
   esac
 done
 
-mkdir -p $DESTDIR
+mkdir -p "${TMPPATH}/repos"
 
 REMOTE="$(sed -Ee 's%^((git(@|://)|http(s|)://)github\.com(/|:)|)%https://github.com/%g' <<< "$REPO")"
 
-case $DLMETHOD in
+case "$DLMETHOD" in
   archive|curl)
     REMOTE="$(sed -Ee "s%(\.git|)$%/archive/${REF}.tar.gz%g" <<< "$REMOTE")"
 
     echo "Downloading $REMOTE ($REF)"
-    curl -#L $REMOTE $EXTRACT | tar xzpf - -C $DESTDIR
+    curl -#L "$REMOTE" "$EXTRACT" | tar xzpf - -C "${TMPPATH}/repos"
     ;;
   git)
-    git clone -b $REF $REMOTE $DESTDIR/$(basename $REMOTE)
+    git clone -b "$REF" "$REMOTE" "${DESTDIR}/$(basename $REMOTE)"
     ;;
 esac
 
-REPO= ; REF= ; EXTRACT= ; REMOTE= ; DESTDIR= ; DLMETHOD= ;
-unset REPO REF EXTRACT REMOTE DESTDIR DLMETHOD
+REPO= ; REF= ; EXTRACT= ; REMOTE= ; DLMETHOD= ;
+unset REPO REF EXTRACT REMOTE DLMETHOD
 exit 0
